#docker load < ffserver.tar.gz
docker load -i ffserver.tar.gz 
docker load -i anpr_yolox.tar.gz
docker load -i face.tar.gz
docker load -i yolox_s_server.tar.gz
docker load -i bytetrack.tar.gz 
docker load -i multi-tenant-python:1.0.6.tar.gz
docker load -i multi-tenant-ui:1.2.54.tar.gz 
docker load -i multi-tenant-server:1.2.37.tar.gz  
docker load -i multi-tenant-ws:1.1.7.tar.gz
